
nothing:


example:
	cat .example_model.rb > ./app/models/my_model.rb

watch_files:
	../demo/files_view.sh

watch_changes:
	../demo/changes.sh

clean:
	rm -r ./migrations
	rm ./app/models/my_model.rb
